[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://animated-dusk-f14e8f.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
