const menu = [
  {
    id: 4,
    title: "Brisket",
    desc: "Slow-smoked to tender perfection for hours, our prime beef brisket boasts a tantalizing bark on the outside and a juicy, melt-in-your-mouth experience on the inside. Expertly seasoned with our secret blend of spices, each bite is a flavorful journey through the artistry of barbecue.",
    type: "Meats",
    special: false,
    price: 17.88,
  },
  {
    id: 1,
    title: "Barebones Burger",
    desc: 'Indulge in the timeless charm of our "Barebones Burger" This culinary masterpiece celebrates the essence of a great basic burger, featuring a perfectly seasoned beef patty grilled to perfection. Nestled within a soft, golden bun, this classic creation is adorned with crisp lettuce, juicy tomato slices, and a dollop of our signature house sauce.',
    type: "Hamburgers",
    special: true,
    price: 9.88,
    specialPrice: 7.5,
  },
  {
    id: 2,
    title: "Bacon Beast Burger",
    desc: "This towering masterpiece is a meat lover's dream, featuring a succulent, flame-grilled patty that promises pure beefy bliss. But that's not all – behold the crispy crown jewel, strips of hickory-smoked bacon, adding an irresistible smokiness and a satisfying crunch to every bite.",
    type: "Hamburgers",
    special: true,
    price: 15.99,
    specialPrice: 11.5,
  },
  {
    id: 3,
    title: "Pretzel Perfection",
    desc: "Picture this: a succulent, flame-grilled patty nestled within the warm embrace of a soft and salty pretzel bun. With each bite, savor the perfect harmony of premium beef, melted cheese, and the rich, distinctive flavor of our secret sauce. Topped with crisp lettuce, juicy tomato slices, and perhaps a hint of pickles, this burger is a symphony of textures and tastes.",
    type: "Hamburgers",
    special: true,
    price: 15.99,
    specialPrice: 11.5,
  },
  {
    id: 5,
    title: "Spare Ribs",
    desc: "Each rack is a masterpiece of flavor, meticulously seasoned and slow-cooked to perfection. Our spare ribs boast a mouthwatering combination of smoky, savory, and sweet notes that dance on your palate with every bite. The meat, tender and juicy, effortlessly pulls away from the bone, delivering a true taste of barbecue excellence. Whether you prefer them slathered in our signature sauce or with the pure, unadulterated flavor of our dry rub, our spare ribs are a celebration of barbecue craftsmanship.",
    type: "Meats",
    special: false,
    price: 19.98,
  },
  {
    id: 6,
    title: "Baby Back Ribs",
    desc: "Indulge in a barbecue experience like no other with our mouthwatering Signature Baby Back Ribs. These premium, lean cuts are carefully selected from the top of the hog's ribcage, delivering an exceptional balance of tenderness and meaty goodness.",
    type: "Meats",
    special: false,
    price: 22.88,
  },
  {
    id: 7,
    title: "Fire-Kissed Classic Hot Wings",
    desc: "Our plump and juicy wings are expertly coated in a zesty blend of spicy seasonings, delivering a perfect balance of heat and flavor. Crispy on the outside, tender on the inside, each bite is an explosion of bold tastes that will ignite your taste buds. Paired with your favorite dipping sauce and served with a side of cooling ranch or blue cheese, these wings are a timeless indulgence for spice enthusiasts.",
    type: "Wings",
    special: false,
    price: 9.98,
  },
  {
    id: 8,
    title: "Pepper Blaze Wings",
    desc: "Embark on a flavor adventure with our Pepper Blaze Wings. These wings are dry-rubbed to perfection with an irresistible blend of bold peppers, creating a symphony of heat and spice that will leave your taste buds tingling. The crispy exterior gives way to juicy, succulent meat, making each bite a journey into spicy delight.",
    type: "Wings",
    special: false,
    price: 15.99,
  },
  {
    id: 9,
    title: "Pulled Perfection Chicken Sandwich",
    desc: "Succulent shreds of slow-cooked chicken, bathed in a savory blend of spices and tenderly pulled to perfection, are piled high on a fresh, toasted bun. Each bite delivers a harmonious medley of smoky, savory, and slightly sweet flavors, creating a symphony for your taste buds. Topped with crisp lettuce, juicy tomatoes, and our signature sauce, this sandwich is a celebration of comfort and culinary craftsmanship.",
    type: "Sandwiches",
    special: false,
    price: 9.88,
  },
  {
    id: 10,
    title: "The Classic Pulled Pork",
    desc: "Immerse yourself in the rich, smoky aroma as you bite into tender, slow-cooked pulled pork, perfectly seasoned and bathed in our signature barbecue sauce. Nestled between soft, freshly baked buns, this sandwich is a tribute to the art of barbecue. Topped with crisp coleslaw for a refreshing crunch, every bite is a journey through the heart of barbecue country.",
    type: "Sandwiches",
    special: false,
    price: 11.99,
  },
  {
    id: 11,
    title: "Mac and Cheese",
    desc: "Our decadent blend of perfectly cooked elbow macaroni and a luscious, velvety cheese sauce creates a symphony of flavors that will transport you to a place of pure indulgence. Topped with a golden, crispy breadcrumb crust for that satisfying crunch, each spoonful is a journey into the heart of comfort food perfection.",
    type: "Sides",
    special: false,
    price: 4.59,
  },
  {
    id: 12,
    title: "Corn Bread Rolls",
    desc: "Crafted with the finest cornmeal and a touch of sweetness, each slice embodies a perfect balance of moist texture and a delicate crumb. The golden exterior gives way to a rich, flavorful center, creating a cornbread sensation that is both comforting and irresistible. Whether paired with your favorite savory dish or enjoyed alone, our Corn Bread Rolls celebrate tradition and taste.",
    type: "Sides",
    special: false,
    price: 3.99,
  },
  {
    id: 13,
    title: "Smoky Maple Baked Beans",
    desc: "Slow-cooked to perfection, our signature blend of tender beans is infused with a rich, smoky essence and sweetened to perfection with a touch of maple syrup. Each spoonful is a delightful balance of savory and sweet, creating a taste sensation that will transport you to the heart of barbecue bliss. Whether enjoyed as a comforting side or the star of your plate, our Smoky Maple Baked Beans are a testament to the art of slow-cooking and the bold flavors that define our culinary tradition.",
    type: "Sides",
    special: false,
    price: 4.99,
  },
];

export default menu;
